### ISSUE TITLE
Not working with HA 0.93.1, ImportError: cannot import name 'STATE_HEAT'

### ISSUE THREAD

**Issue by MagicFab** [lrogoff/sinope#3]
I'm testing a standard Home Assistant install under Debian Stretch. This may be related to [the recent changes and improvements to integrations as indicated here](https://developers.home-assistant.io/blog/2019/04/12/new-integration-structure.html).

When starting hass this is shown in the log:
2019-05-22 13:53:53 ERROR (MainThread) [homeassistant.loader] Error loading custom_components.sinope. Make sure all dependencies are installed
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/loader.py", line 263, in _load_file
    module = importlib.import_module(path)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/root/.homeassistant/custom_components/sinope.py", line 15, in <module>
    from homeassistant.components.climate import (ClimateDevice, PLATFORM_SCHEMA, STATE_HEAT, STATE_IDLE, ATTR_TEMPERATURE, ATTR_AWAY_MODE, SUPPORT_TARGET_TEMPERATURE)
ImportError: cannot import name 'STATE_HEAT'

**Comment by zetvio** [comment]
This repo hasn't been updated since a while. See this fork [here](https://github.com/claudegel/sinope-1), it's up to date and works with HA 0.93.1

You can also follow [this thread](https://community.home-assistant.io/t/sinope-line-voltage-thermostats/17157) to get updates about this project.
